### ISSUE TITLE
TRex crashes on video "Open"

### ISSUE THREAD

**Issue by JepsonNomad** [mooch443/trex#1]
Hi there - I'm trying to get TRex running on some footage I collected this summer. It seems that once I navigate to a folder, TRex doesn't see the video files in it, and I have to manually enter the filepath (whereas going through folders can be point-and-clicked). Then, when I try to Open the video and get started, TRex crashes. I've found this to be the case for both .mov and .mp4 videos. Here is the splash screen:

<img width="1412" alt="Screen Shot 2020-10-16 at 2 42 01 PM" src="https://user-images.githubusercontent.com/33075946/96311229-df07d480-0fbd-11eb-8133-5ab5ddc23e21.png">

MacOS Catalina v10.15.6
2.8 GHz Quad-Core Intel Core i7
Installed using conda create -n tracking -c trexing trex

**Comment by mooch443** [comment]
Hey there! Thanks for trying out TRex. I have noticed that it's an easy mistake to make, but you'll have to convert the video first -- that's why they don't show up. Currently, conversion is still done in tgrabs - in a future version it will work as you expected.

A good start is probably the examples section of the docs:

￼https://trex.run/docs/examples.html

**Comment by JepsonNomad** [comment]
Ah thanks a lot. I hadn't realized tgrabs was a precursor.

**Comment by mooch443** [comment]
Yes, but as soon as you figure out tracking parameters that work for you, then converting/tracking can be done at the same time in TGrabs (using -enable_live_tracking). I'll add docs for that soon.
