### ISSUE TITLE
Orientation Swaps

### ISSUE THREAD

**Issue by beccirooke** [mooch443/trex#15]
Hello. Thanks for this awesome software!

I am tracking fruit flies and notice that the orientation of the flies (head vs tail) is inconsistent and occasionally rapidly swaps back and forth on a stationary individual.

I've tried altering some settings, including:  setting peak_mode to broad and posture_direction_smoothing to true.
None of these changes improved the orientation predictions.

Are there any other settings you would recommend I change?

Thanks again!

**Comment by mooch443** [comment]
Hey! Glad you like it!

Hm, I would probably stay away from posture_direction_smoothing, since its implementation isn't _that_ great. Do you have a screenshot? That would help to determine whats wrong. I think it is likely that the flies are too small, and you could try changing outline_resample to 0.5 in your videos. You can also have a look at this config file I used for flies before:

```
blob_size_ranges = [[0.015,0.175589]]
blob_split_global_shrink_limit = 0.025
blob_split_max_shrink = 0.3
midline_invert = true
midline_stiff_percentage = 0.25
midline_walk_offset = 0.1
outline_curvature_range_ratio = 0.1
outline_resample = 0.5
outline_smooth_samples = 10
track_max_individuals = 59
track_max_speed = 15
track_speed_decay = 0.95
```

Where the most important ones are the ones for outline and midline. Not saying these are necessarily the values you should use, but definitely the kind of parameters that are important.

Hope this helps!

**Comment by beccirooke** [comment]
Thanks so much for the quick response. I will play around with the outline and midline parameters.

I was a little worried that my flies would be too small. I've attached a screenshot for reference.

LOVING how well the program tracks identities though.
![Screenshot](https://user-images.githubusercontent.com/79878232/109571488-c229f480-7ab9-11eb-9ccf-c7756bc70e6b.png)

**Comment by mooch443** [comment]
No worries! They do look small indeed. Maybe even `outline_resample` of `0.25` in this case. Your `track_threshold` could be a bit higher as well, if you want smoother shapes. 

Hope this helps -- if it does, feel free to report what you've had to change and close the issue. This might also help others in the future, or me to update the documentation (which is still actively evolving). Not as fast as those flies though!
