### ISSUE TITLE
How is neighbor distance calculated?

### ISSUE THREAD

**Issue by jptumulty** [mooch443/trex#154]
On the https://trex.run/docs/formats.html page it says NEIGHBOR_DISTANCE is the average euclidean distance to neighbors. I tracked a video with 2 individuals, so I would expect neighbor distance to be the same for both individuals in the video - their neighbor distances are correlated but not identical. So, I am curious how, exactly, it is calculated?

Basically, I want to track the distance between individuals based on something like the minimum distance between their outlines. 

And for videos with more than 2 individuals, would it be possible to get pairwise distances between each individual? I realize I can get distances between centroid or head position, was just curious if I could get it from outline points.

Thanks very much!

**Comment by mooch443** [comment]
Hey, not sure this is still relevant since I didn't get to the GitHub issues in quite a while. But anyhow, it's basically the average distance to all other individuals. The relevant code is this here verbatim ([OutputLibrary.cpp:433](https://github.com/mooch443/trex/blob/4490f6de3f5f0b1ffbe10f300412e1729b79a3e3/Application/src/tracker/misc/OutputLibrary.cpp#L433)):

```c++
float d = 0.0;
float samples = 0;

const MotionRecord *oc;
for (auto other: individuals) {
    if (other != fish && (oc = other->centroid(frame))) {
        auto opos = oc->pos<Units::CM_AND_SECONDS>();
        d += euclidean_distance(pos, opos);
        samples++;
    }
}

return samples > 0 ? d / samples : gui::Graph::invalid();
```

There you will also find all of the other possible outputs, in case you need to know what they do :-)
