### ISSUE TITLE
Coordinate Unit Clarification

### ISSUE THREAD

**Issue by pashatab1** [mooch443/trex#18]
Hello - 

After tgrabs and trex, I export the tracking results and I am able to read the .npz files. However, I can't seem to figure out the unit associated with the coordinates X and Y. My raw data video is ~1800x1800px^2 and all of my coordinates fall within a box of ~30x30 (units unknown). 

I have not changed any parameters associated with the image size from their default value. I've browed the documentation and see a couple parameters (meta width, for example) but can't seem to follow the logic. 

Could you clarify the units or the method used to scale the raw pixel positions? That would be helpful for me. It might also be helpful for others if this is more straightforward. Or if this info is already provided, could you point me to it?

I appreciate your help,
Pasha

**Comment by mooch443** [comment]
Hey,
glad that you've got it to work!

When you convert videos (or in a more complicated way post-converting) you can set the "meta_real_width" parameter to your arena width in cms (or rather: width of everything you can see from left to right of the video image in cm). This is then used to convert between pixels and cms - the unit of extracted X and Y coordinates is supposed to be cm. Of course, this only works if you set `meta_real_width` to the correct value. Otherwise the default value of `30` is used - hence your results. This formula is used to calculate the unit-conversion factor `cm_per_pixel`:

```
cm_per_pixel = meta_real_width / px_width_of_video_image
```

It is automatically calculated in TRex/TGrabs during startup based on `meta_real_width` in the video file. `cm_per_pixel` can be changed directly as well during startup of TRex (e.g. command-line parameter), but since arena size won't change ever I'd rather adjust `meta_real_width` during conversion. Whenever a X/Y-position is output (or indeed also used for parameters like `track_max_speed`, which is in cm/s), the conversion from px to cm is done by:

```
X(px) * cm_per_pixel(cm/px) = X(cm)
```

Hope this helps! I will update documentation accordingly in the next couple of days and close the issue unless you have something else related to this :-)
-Tristan

**Comment by pashatab1** [comment]
Thanks for the fast reply Tristan. 
I will put this info into action over the next day or two. I have one follow up question - if the frame is rectangular, is meta_real_width expected to be the real space length (in cm) of the 1) image width, 2) short side etc.? I imagine the answer is #1, and I would, for example, have to change meta_real_width if I rotate the rectangular video by 90 degrees?

Pasha

**Comment by mooch443** [comment]
It is always the width. So no matter what you do, use the real size of the thing that you put through TGrabs in X direction!
