### ISSUE TITLE
An alternative solution for calibrating cm_per_pixel

### ISSUE THREAD

**Issue by roaldarbol** [mooch443/trex#24]
**Is your feature request related to a problem? Please describe.**
The current solution of using meta_real_width is somewhat limiting, eg. when there are height differences because of walls, and often you may know a certain distance within the frame instead. It would be very useful to have an alternative way of getting cm_per_pixel.

**Describe the solution you'd like**
The TRex GUI already allows you to click and obtain coordinates within the frame, so an easy solution could be a function where you provide 2 coordinates with a known distance between them (or asks you to click on two coordinates, then asks for the distance).

**Additional context**
This type of feature is common in ImageJ, tracker, and other image processing software which requires the user to specify a known length within the image/video ([example](https://physlets.org/tracker/help/frameset.html) from tracker, calibration stick). The function could default to False, and if provided cm_per_pixel could use it instead of meta_real_width. It requires a bit of basic pythagorean calculation, but shouldn't be very hard to incorporate.

**Comment by mooch443** [comment]
I agree. This has come up a couple of times now already and it would be logical to extend the functionality that I already have in there. You can select multiple coordinates already, by holding the shift key and clicking multiple points - selecting more than two triggers a Button to pop up (depending on version) and add a shape to either `track_ignore` or `track_include`. It should be rather easy to set it up so that it will trigger a "cm_per_pixel" dialog. Adding to current milestone.
Thanks for reporting!
