### ISSUE TITLE
blob_split

### ISSUE THREAD

**Issue by StefanMPopp** [mooch443/trex#55]
1) The `blob_split_global_shrink_limit` and `blob_split_max_shrink` have a default value of 0.2 listed in the documentation but my TRex output indicates them being 0.4.

2) How is decided which threshold is used when splitting blobs? Whichever is smaller?

**Comment by mooch443** [comment]
1. Which version (build) of TRex are you using? Maybe, if you're using an older one, the default value has since changed. With no additional information, however, I can only guess.
2. Not sure if this was your question, but `track_threshold` always comes before `track_posture_threshold`. I am aware of potential problems with this, e.g. you may want to separate individuals with a higher threshold and then still regain most pixels with a lower posture-threshold, but (despite the risk of sounding lazy) it works in most cases and was the most straight forward to implement - as well as avoiding some ambiguities with post-hoc pixel assignment when objects are already separated.

**Comment by StefanMPopp** [comment]
Oh, with 'threshold' I meant which of the two `shrink` values are used (or how they interact).

**Comment by mooch443** [comment]
Yes, that's indeed one of the portions of the program thats a bit obscure, sorry. So the docs have this to say about the two: https://trex.run/docs/parameters_trex.html#blob_split_global_shrink_limit - but if you want to disable automatic blob splitting, you should set both shrink values to 1.0.
