### ISSUE TITLE
Directional data

### ISSUE THREAD

**Issue by MarkJThomas** [mooch443/trex#66]
Hiya, 
I just wondered if there was a way to know if my subject was moving left or right. Basically, food is left, nest is right, when under stress (or not) I wanted to see if they are moving more left than right, and then look at speed average. 

![Screenshot 2021-08-26 at 10 30 06](https://user-images.githubusercontent.com/41441629/131101479-f46794c4-3af9-4ec3-b6cb-46e7b65d57bd.png)

Which data from the .npz file would give me that information?
And is there a way to calculate distance covered?

Here is a screenshot of the ants, square boxes is blocking of the tunnel where they seem to meet and greet quite a lot.

Thanks in advance!
Mark

**Comment by MarkJThomas** [comment]
Hi @mooch443 
Hope you are well. I appreciate that you are doing this off your own back, and the system is revolutionary for the work I am doing.
I just wondered if you had seen/can respond to the above question?
All the best,
Mark

**Comment by mooch443** [comment]
Hey, yes, you're right - this is basically on my free time right now, but I want to help whenever I can.
So if you're trying to see the speed in x-direction (the velocity), you can use VX from the npz file, which is exactly that. You can of course try to fix the posture data so far that you can use it. Not sure how well it performs on those - I suspect you would have to increase the ``track_posture_threshold`` quite a bit for it to work. Pro-Tip: You can always check using ``track_threshold`` to see if a certain threshold value works as intended (cuts off enough of the animals, like the legs and antennae) and then set this value for ``track_posture_threshold`` - and reset ``track_threshold`` to what you had before. I'll make this easier in 2.0, so stay tuned I guess!

The question would be whether VX is already enough (or you could calculate VX yourself by using the X-positions), or if you need posture to work reliably. I think VX should suffice in your case, though, unless you say otherwise.

If you want to calculate distance covered, you could do sum(SPEED * time') for a certain range of frames, no? You just have to modify it somehow so that you have one value per fix sequence length or something. If that's what you need :D

-Tristan

**Comment by MarkJThomas** [comment]
Perfect, thank you so much!
I did have something that come up with my supervisor, is there a way to calculate how far they move off the straight line between the two white boxes in my image? I see there is midline_x, midline_y, and midline_offset, and normalized_midline. What I would like to see is how far they offset from the midline under different treatments.

**Comment by mooch443** [comment]
Hey! There is no way to do this, no. However, there is a way in Python that I can share if you are interested. Instead of assigning the same number, you would get a dataframe with IDs per segment (so as you suggested).

```
segID = 0
DF = None
video = "video_name"
base_path = "/root/path"

output = output_dir+os.sep+video+".pkl"
files = glob.glob(base_path+os.sep+"data"+os.sep+video+"_fish*.npz")
if len(files) == 0:
    raise Exception("No data for video",video)
    
print("\tFound",len(files),"files.")

j = 0
for path in sorted(files):
    index = path.split(os.sep)
    index = int(index[-1].split('_fish')[-1].split('.')[0])

    j = j + 1
    if j%100 == 0:
        print(j,"/",len(files),path,"individual",index)

    with np.load(path) as npz:
        frame_segments = npz["frame_segments"]
        frame = npz["frame"].astype(int)
        m = {
            "id": np.repeat(index, len(frame)),
            "frame": frame
        }
        
        for c, k in columns:
            m[c] = npz[k]
            m[c][np.isinf(m[c])] = np.nan
            #print(m[c].shape)


        segIDs = np.full(len(frame), -1, dtype=int)

        for start, end in frame_segments:
            if end - start >= segment_threshold:
                segIDs[np.logical_and(frame >= start, frame <= end)] = segID
                segID += 1

        m["segID"] = segIDs

        df = pd.DataFrame(m)
        if type(DF) == type(None):
            DF = df
        else:
            DF = pd.concat((DF, df), ignore_index = True)

DF # your dataframe
```
