### ISSUE TITLE
Collision detection

### ISSUE THREAD

**Issue by listenaddress** [mooch443/trex#67]
Hey, thanks for the rad tool Tristan!

I'm trying to detect [collisions of tadpoles](https://github.com/jstremme/trex-cv-experiments). Specifically I'm looking to find velocity and displacement caused by collisions.

Looks like we're getting a lot of the data needed to make these calculations (amazing!!), but I'm wondering if you've seen any related use cases implemented already?

**Comment by mooch443** [comment]
Hey, Thanks!!
Nice looking repository you got there. Unfortunately I am not aware of any similar projects so far - but it certainly sounds interesting. Do you think there's anything missing right now from TRex which would make this easier?

**Comment by listenaddress** [comment]
Good question. If others have this use case, a method that returns the frames/animals/coordinates of collisions/overlaps could be handy. We have that logic working, in case you're interested. 
 
A bit off topic of the issue, but my biggest questions right now are around improving the accuracy. I'm wondering... 
- What kind of accuracy would you expect to be able to get on a video like the one below?
- How would you go about improving accuracy?

Example of actual video
![tadpole footage](https://user-images.githubusercontent.com/8434548/137605956-d779021d-1d68-4006-b97f-5071a3be9abd.gif) 

In Trex
![Oct-16-2021 20-50-08](https://user-images.githubusercontent.com/8434548/137605844-5bd20dfb-2866-4476-a525-62b5479eaa07.gif)

**Comment by mooch443** [comment]
I would expect better results from this for sure. Do you have a full scale sample for me to work on? You can send it via E-Mail as well, if you prefer. Otherwise, this is what I achieved with your gif. (I had to edit the background image since it had some artifacts, and there could be TGrabs options that can be used to improve the conversion quality - e.g. use_closing. These artifacts occur because the video is only 60 frames long and the individuals cannot be averaged out completely).

![clip2](https://user-images.githubusercontent.com/2864719/142652528-92ba9ff8-ab88-4dad-9495-39ae238be86e.gif)

Conversion background image:
![average_137605956-d779021d-1d68-4006-b97f-5071a3be9abd](https://user-images.githubusercontent.com/2864719/142652700-ac7bbd3a-4dc7-41bd-9af3-09c6b70b616f.png)

Tracking settings:
```
blob_size_ranges = [[0.08,0.3]]
gui_zoom_limit = [100,100]
track_threshold = 66
```
