### ISSUE TITLE
Comparison of tracks with video frame in tracking view

### ISSUE THREAD

**Issue by kate-bowers** [mooch443/trex#71]
**Is your feature request related to a problem? Please describe.**

I get imperfect blobs with TGrabs (sometimes multiple are included in one blob, sometimes a subject is missed) so when looking at tracks, I want to make sure that all of the subjects in view are accounted for correctly. It's frustrating to not be able to compare the tracks to the base video; I have no idea how accurate these tracks are to my data.

**Describe the solution you'd like**

When I scan through tracks in tracking mode, I would like to see the corresponding video frame instead of just the background image.

**Describe alternatives you've considered**

The best option I can think of is to pull up the video next to my Trex window and try to match them up by time, then compare the contours with the video. This can generally show if individuals are untracked, but it would be very useful to be able to see the contours superimposed over the actual base video frame to see how well each animal is tracked.

**Additional context**
Thank you! This is a really compelling project.

**Comment by mooch443** [comment]
Hey, thank you for your report.

This sounds to me like a "validation" project, more or less. I am guessing you would do this once, more or less, to verify that you can trust it. And then not again? Since once you trust it, you could just use it, right? I would split this into two parts and answer each question individually:

1. **Is it possible to validate whether all individuals are successfully tracked, or whether some of them (visible in the original video) do not appear in the tracking results?** This is a bit difficult, but... usually you would, even if the animals are not successfully recognised/thresholded away, see some part of them in the RAW view. This is what you can toggle in TRex by pressing D (to enter debug/RAW mode or normal). It also shows you the sizes of individuals, etc. Usually, if its due to threshold (the worst), then you will still see some remaining smear of this animal there - if not, then you have a more complicated case. Like, when individuals can be vastly different colors/brightnesses. There is no option to include the full video frame, since this defeats the entire purpose of preprocessing (videos can be very slow to read). However, if you just wish to do this once/twice/for a subset of videos: You can start with this https://github.com/mooch443/trex/blob/master/docs/scripts/plot_posture_output.py script, and extend it to include the original video frames (if you also generate postures). I might include a script for this soon, but I will answer you here first. Basically the script behind the link, but add in a cv::VideoCapture and read frame by frame, display the frame as the background - voiá.
2. **Is it possible to validate how accurate the contours are?** No. Unless you have manual validation data/just want to do it visually. Depending on your outline_approximate setting, however, this will be more or less intentionally inaccurate. If you disable it (=0) then you will get pixel perfect contours. The same goes more or less for positions, which you could only validate with manual data (e.g. in a Python script) or through visual inspection, which is - I would think - what you mean. This could be done e.g. via the script I mention above, also including posture.

Hope this helped! I can consider including an option to display the video alongside it, but that would also imply a lot of adjustments for all kinds of options like scaling, cropping, etc., so its not trivial.
