### ISSUE TITLE
Correcting Old Imgstores With Incorrect Size

### ISSUE THREAD

**Issue by nzjrs** [mooch443/trex#8]
FWIW Instead of the fix you have

https://github.com/mooch443/trex/blob/586ce986c56e5746aba898ba89a5e2cedacb11bc/Application/src/commons/common/video/VideoSource.cpp#L374-L379

You can take the same fix we have, which doesn't require opening / reading the first movie

https://github.com/loopbio/imgstore/issues/12
https://github.com/loopbio/imgstore/blob/444fc61bd7cd00e1ec8cd1bc3cab51f7bcc59352/imgstore/stores.py#L1015

which is basically `shape &= -2` to truncate to even because the underlying cause was me not respecting+checking h264 size limitations

**Comment by mooch443** [comment]
Hey! Thanks for this much more elegant fix. Do you _always_ restrict sizes to even? I suppose there could be codecs that do not have the same restrictions.

**Comment by nzjrs** [comment]
Oops, I missed your question. That size limitation is certainly true for 420 (and 444 IIRC) h264 streams which were always written under those codec identifiers. Since then we have introduced new codecs without this limitation and in those cases we ensured that the correct size is written in the metadata and so can be trusted.

You commit mentions the metadata in the npz files. I guess this is a typo as the metadata is written into the yaml files https://github.com/loopbio/imgstore/blob/master/imgstore/tests/data/store_mp4/metadata.yaml - the npz files hold the frame time and framenumber information.

**Comment by mooch443** [comment]
No worries, thanks for answering! I am (maybe incorrectly) referencing the fact that I can read the "format" string that's inside the individual npz files (containing e.g. "nvenc-[...]"). I had to write a clunky custom function (it trusts that you know it's a string) to read out char arrays properly from NPZ files, since cnpy does not seem to support that. But its similar to the selector you use in your code to determine whether to crop:
https://github.com/loopbio/imgstore/blob/444fc61bd7cd00e1ec8cd1bc3cab51f7bcc59352/imgstore/stores.py#L1002

**Comment by nzjrs** [comment]
OK fair enough. As you see I keep duplicates of the metadata in the NPZ files but that's not strictly part of the file format - the metadata.yaml should be considered the canonical source of that. But if you don't have a yaml parser/dep in your codebase then the NPZ trick will work.
