### ISSUE TITLE
Combining Blobs

### ISSUE THREAD

**Issue by Ace5225** [mooch443/trex#86]
Hey, I am having an issue where some of my fish are getting separated into two or more blobs, this is putting them below the threshold, which is no issue to just match them manually. But is there a way to assign multiple blobs to one fish, this way I could get a more accurate reading of the center of the fish? I've tried adjusting the threshold for pixel values as I assume it is mostly caused by some dropped pixels in the fish causing it to separate into two blobs but I have had limited success in doing so.

Thank you for all your work, this has been invaluable to our project!

**Comment by mooch443** [comment]
Hey,
unfortunately there is currently no way to assign multiple blobs to one fish in a single frame, sorry! It would be good to look into why they are being separated into multiple blobs, though. Are you using complicated images or is there good contrast between the individuals and the background? If its too close, you could try to pass additional flags during conversion (e.g. ``-use_closing``), increase the threshold there and then simply track them with a very low threshold. Usually that's the reason - or because they are closeby other individuals and threshold is adaptively increased (which can be disabled).
Hope I could help anyway! :-)
