### ISSUE TITLE
blob_size_range flag affected by junk files within the current directory causing a crash

### ISSUE THREAD

**Issue by aperkes** [mooch443/trex#93]
**Describe the bug**
I was getting very strange behavior with tgrabs where it failed to process the video if I specified "-blob_size_range" Eventually I realized it only happened when I was running from within a sub directory, not from my home directory, even though in both cases I specified the full path.  On further investigation, I noticed that I had a empty file called '2' in my directory (apparently generated by a sloppy batch script I'm debugging.) Obviously this is a very specific problem, but it might reveal some underlying vulnerability. 

**To Reproduce**
-create an empty file within your current directory with "2" as the filename (e.g. "touch 2") 
-run tgrabs using the -blob_size_range argument

you get the following error: 
> terminate called after throwing an instance of 'cmn::illegal_syntax'
>  what():  Cannot parse array '2'
>  Aborted (core dumped)

Moving to a different directory, or dropping the -blob_size-range argument removes it. Deleting the empty file, or renaming it (e.g., 2.txt) also fixes it. Interestingly, this also occurs if you have a file called '1' but not '3'. I haven't tried any other numbers. 

**Computer (please complete the following information):**
 - Operating system: Ubuntu 18.04.06
 - Build hash 0c4577eed732fe8f2c9d8deee969dc8ee71fac50
 - Terminal used: bash

**Comment by mooch443** [comment]
Hey, thanks for reporting this. I do not think that the contents of the current folder could influence this _within TGrabs_, but outside of it I do. Did you check whether it helps to put the argument for `blob_size_range` in quotes? I've had problems with this on windows mostly, but maybe your terminal does something similar: Some terminals are a bit weird with brackets, and they might see it as part of the bash/batch script language instead of as a command argument. So instead of

``tgrabs -blob_size_range [0.5,5]`` you would do ``tgrabs -blob_size_range "[0.5,5]"``

Maybe this resolves the issue :-)
