### ISSUE TITLE
Parquet file output format

### ISSUE THREAD

**Issue by roaldarbol** [mooch443/trex#94]
**Is your feature request related to a problem? Please describe.**
As tracking projects get bigger, so do file sizes. Apache Parquet is over 10 times faster than CSV, less than half the size (at least). 

**Describe the solution you'd like**
Option to output data in parquet format. Both the R and Python packages are very easy to use and could easily be implemented (I believe).

**Describe alternatives you've considered**
Writing abash + R script that imports the CSV file, saves them as parquet files and deletes the original CSV. 

**Additional context**
Some good links and info in this tweet: https://twitter.com/datalorax_/status/1491647741042180097?s=20&t=QOpk4iWKjN2lJypxFxzv5A

**Comment by mooch443** [comment]
Hm. I've had a look at some of the documentation/repositories of the library, and it seems like it comes with a whole bunch of dependencies. I am currently not feeling comfortable adding this in. There are also NPZ libraries [that can be used in R](https://cran.r-project.org/web/packages/RcppCNPy/vignettes/UsingReticulate.pdf) (and NPZ is natively supported by numpy in python). It might be possible to integrate h5 (since its already a python-dep), or even parquet, at some point - so I'll leave this open.

**Comment by roaldarbol** [comment]
Ah fair enough, too bad about the dependencies. I'll just continue to reformat them manually, no trouble in doing that. :-)
